git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
 - '4'
 - '5'
 - '6'

before_script:
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"
script: npm run ci

notifications:
  slack:
    secure: hN85OnXgLdmtpBEhB7J7UZfEsvC4GBk6y4FFxItw6OVtehZR++0eSM2mxArQN7g8doUX1BkD6finNWEidQPNHwQJdkw7cjNHf984lNw0Uc7eGXoLyJaEXTz2Y8HNb7y2J0+RMnyFvEvnyKmm/Gvn16Rj8vrdglhQVPd+sVIpxv4T0dq3JKnuQqAeQM2tfgyhOduZFHH/3RZqS/JBsecyOjWlo6b0A5AUmEuc3CzqWIU0+welwZ9blxiitTxCQuX113kzy4bedkHzakAMeE8TUXD4JdLbKn180bCm3WhE3IuM2Xr18NOPw2ANQFoyAm6h/BFUm/8NFOtTsIDggN4tnZ2Okr2hkvl1KkpfoHLqQUQNepSaQsgBslUpf+6vxCIKQ2umDJSRtcXw31IJjT5XX8iPn24v83Z6lX5Dq7PL88m8y7/5juPakvP5EE61B5lTq3QdJZh/wUOahEPdeAFOHfwT21TMEE9Y/V5Dcx8Y5sNu2G1jQsQFyf3OnLvwhh1aYsw6xYEReWN+h1refcIiK7AD6ajlUK7xZG38RK3gF1UQOT5bmOwpd1gaPihOmGeQdS1GaGe+gg/DE5rXG78xtRWmW+TJ6uWyTgQlFxQLA57mVIbf1cemP6hnrMmE/VZxrvkvybYW90eOX+48TcZBWjONt9GUGN+57nIjwRmiH3c=
