# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "6"

init:
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g asini

test_script:
  - node --version
  - npm --version
  - asini run test

# Don't actually build.
build: off

notifications:
  - provider: Slack
    incoming_webhook:
      secure: "in+scOGov0C+4+TOtI66odvLe0yGUlmm/y4r+F1U6l/Zo9+m84idfiL2G5dvAQb39Na36z+CyC5FAx/6EcKQm/9KXU28txOab25Ke5havKs="
